repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files
    - id: check-merge-conflict
    - id: check-case-conflict

- repo: https://github.com/pycqa/isort
  rev: 5.10.1
  hooks:
  - id: isort
    name: isort

- repo: https://github.com/pycqa/flake8
  rev: 4.0.1
  hooks:
  - id: flake8
    name: flake8
    additional_dependencies:
    - flake8-bugbear
    - flake8-no-pep420
    - flake8-comprehensions
    - flake8-docstrings

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: 'v0.940'
  hooks:
  - id: mypy
    name: mypy
    exclude: ^tests/test_.*
