name: pre-commit

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - 'master'

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - uses: pre-commit/action@v3.0.0
